version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16 # Uses Postgres 16 with pgvector pre-installed
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge_base
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  web:
    build: .
    platform: linux/amd64
    #env_file:
      #- .app_env
      #- .docker-env
    volumes:
      - .:/usr/src/app
    ports:
      - "8002:8000"
    depends_on:
      - db

#volumes:
  #postgres_data:
